# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: envio-indexer
disable_default_cross_chain: true
chains:
- id: 42161
  start_block: 501626000
  contracts:
  - name: FiatTokenProxy
    address:
    - "0xaf88d065e77c8cC2239327C5EDb3A432268e5831"
    events:
    - event: Approval(address indexed owner, address indexed spender, uint256 value)
    - event: Burn(address indexed burner, uint256 amount)
    - event: Mint(address indexed minter, address indexed to, uint256 amount)
